services:
  - type: web
    name: global-stock-screener
    env: python
    plan: free
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.fileWatcherType none --runner.fastReruns true
