services:
  - type: web
    name: global-stock-screener
    env: python
    plan: free
    rootDir: .
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: STREAMLIT_SERVER_FILE_WATCHER_TYPE
        value: "none"
      - key: STREAMLIT_RUNNER_FAST_RERUNS
        value: "true"
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.fileWatcherType none --runner.fastReruns true
